name: release-fpga
on:
  workflow_dispatch:
    inputs:
      version:
        description: VERSION
        required: true
jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true
    - name: Build 'Intel FPGA' runtime
      uses: docker://buildpack-deps:precise
      with:
        args: make intel-fpga
    - name: Build 'Xilinx FPGA' runtime
      uses: docker://buildpack-deps:precise
      with:
        args: make xilinx-fpga
    - name: Package archive
      run: tar cvz -f fpga.tar.gz *-fpga
      working-directory: configs
    - name: Release archive
      uses: softprops/action-gh-release@v1
      with:
        body: |
          ```
          curl -sS https://setup.inaccel.com/runtime/fpga | sh -s ${{ github.event.inputs.version }}
        files: configs/fpga.tar.gz
        tag_name: fpga-${{ github.event.inputs.version }}
    - name: Package Debian
      uses: docker://goreleaser/nfpm
      env:
        VERSION: ${{ github.event.inputs.version }}
      with:
        args: pkg --config nfpm-fpga.yaml --packager deb
    - name: Package RPM
      uses: docker://goreleaser/nfpm
      env:
        VERSION: ${{ github.event.inputs.version }}
        RELEASE: 1
      with:
        args: pkg --config nfpm-fpga.yaml --packager rpm
    - name: Push Debian
      uses: cloudsmith-io/action@master
      with:
        api-key: ${{ secrets.CLOUDSMITH_API_KEY }}
        command: push
        format: deb
        owner: inaccel
        repo: stable
        distro: any-distro
        release: any-version
        file: '*.deb'
    - name: Push RPM
      uses: cloudsmith-io/action@master
      with:
        api-key: ${{ secrets.CLOUDSMITH_API_KEY }}
        command: push
        format: rpm
        owner: inaccel
        repo: stable
        distro: any-distro
        release: any-version
        file: '*.rpm'
